### ISSUE TITLE
Release chart worklfow is failing

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/repo-helm-charts#11]
![image](https://user-images.githubusercontent.com/54287612/172584908-764cb91f-c625-4d57-ae33-2a431c74e249.png)

**Comment by stefanaz** [comment]
@NishaSharma14 just a guess, but it may be that `postresql` helm chart which you have in dep., has no that version any more. 

![image](https://user-images.githubusercontent.com/8876063/172615262-7ca5f44f-b61d-4193-99ac-857afae3e564.png)

It seems that bitnami has limited list of versions and version 10.13.11 is not in their list any more. (check [here](https://artifacthub.io/packages/helm/bitnami/postgresql))

**Comment by NishaSharma14** [comment]
Thanks @stefanaz , your guess was right. :)
